# Generated by Django 5.1 on 2025-12-29 04:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bkashpayment',
            options={'verbose_name': 'BKash Payment', 'verbose_name_plural': 'BKash Payments'},
        ),
    ]
