# Generated by Django 5.1 on 2025-12-31 03:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_otp'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='otp',
            name='purpose',
        ),
    ]
