# Generated by Django 5.1 on 2025-12-31 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_remove_otp_purpose'),
    ]

    operations = [
        migrations.AddField(
            model_name='otp',
            name='purpose',
            field=models.CharField(choices=[('verification', 'Email Verification'), ('reset', 'Password Reset')], default=1, max_length=20),
            preserve_default=False,
        ),
    ]
